[settings]
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[tools]
doppler = "latest"
glow = "latest"
jj = "latest"
node = "latest"
"npm:agent-browser" = "latest"
prek = "latest"
terraform = "latest"
"ubi:anchore/grype" = "latest"
"ubi:anchore/syft" = "latest"
"ubi:sxyazi/yazi" = "latest"
yazi = "latest"
terragrunt = "latest"
go = "latest"
ruff = "latest"
atuin = "latest"
"cargo:kanata" = "latest"
eza = "latest"
"ubi:astral-sh/uv" = "latest"
"ubi:astral-sh/ruff" = "latest"
lazygit = "latest"
lazydocker = "latest"
gum = "latest"
yq = "latest"
"ubi:muesli/duf" = "latest"
"ubi:bcicen/ctop" = "latest"
"ubi:aristocratos/btop" = "latest"
fd = "latest"
bat = "latest"
ripgrep = "latest"
fzf = "latest"
sops = "latest"
age = "latest"
bitwarden = "latest"
starship = "latest"
zoxide = "latest"
